repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: check-added-large-files
          - id: check-json
          - id: check-toml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace

    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: "v21.1.2"
      hooks:
          - id: clang-format
            files: \.(c|cc|cpp|cxx|h|hh|hpp|hxx)$

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.14.1
      hooks:
          - id: ruff-check # linter
            args: [--fix]
          - id: ruff-format # formatter
            files: \.py$
