[project]
name = "vision-foundry"
version = "0.1.0"
description = "Python wrapper around vision foundry core"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "vision-foundry-core",
]

[tool.uv.sources]
vision-foundry-core = { path = "../cpp" }
