[project]
name = "vision-foundry-py"
version = "0.1.0"
description = "Python wrapper around vision foundry project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
